// Generated by scripts/design-system.mjs. Do not edit.
import * as stylex from "@stylexjs/stylex";
import { colors } from "../../styles/Colors.stylex";
import { spacing } from "../../styles/Spacing.stylex";
import { fontFamilies } from "../../styles/Typography.stylex";
import { fontSizes } from "../../styles/Typography.stylex";
import { fontWeights } from "../../styles/Typography.stylex";
import { lineHeights } from "../../styles/Typography.stylex";
import { letterSpacing } from "../../styles/Typography.stylex";
import { radii } from "../../styles/BorderRadius.stylex";
import { shadows } from "../../styles/Shadows.stylex";

export const specimens = stylex.create({
  "colors.background": {
    backgroundColor: colors.background,
  },
  "colors.surfaceSubtle": {
    backgroundColor: colors.surfaceSubtle,
  },
  "colors.surface": {
    backgroundColor: colors.surface,
  },
  "colors.surfaceHover": {
    backgroundColor: colors.surfaceHover,
  },
  "colors.border": {
    backgroundColor: colors.border,
  },
  "colors.textMuted": {
    backgroundColor: colors.textMuted,
  },
  "colors.textSecondary": {
    backgroundColor: colors.textSecondary,
  },
  "colors.textStrong": {
    backgroundColor: colors.textStrong,
  },
  "colors.textPrimary": {
    backgroundColor: colors.textPrimary,
  },
  "colors.accentSoft": {
    backgroundColor: colors.accentSoft,
  },
  "colors.accentText": {
    backgroundColor: colors.accentText,
  },
  "colors.accentSurface": {
    backgroundColor: colors.accentSurface,
  },
  "colors.accent": {
    backgroundColor: colors.accent,
  },
  "colors.accentForeground": {
    backgroundColor: colors.accentForeground,
  },
  "colors.actionPrimary": {
    backgroundColor: colors.actionPrimary,
  },
  "colors.actionPrimaryHover": {
    backgroundColor: colors.actionPrimaryHover,
  },
  "colors.actionPrimaryText": {
    backgroundColor: colors.actionPrimaryText,
  },
  "colors.actionSecondary": {
    backgroundColor: colors.actionSecondary,
  },
  "colors.actionSecondaryHover": {
    backgroundColor: colors.actionSecondaryHover,
  },
  "colors.actionSecondaryText": {
    backgroundColor: colors.actionSecondaryText,
  },
  "colors.actionDanger": {
    backgroundColor: colors.actionDanger,
  },
  "colors.actionDangerHover": {
    backgroundColor: colors.actionDangerHover,
  },
  "colors.actionDangerText": {
    backgroundColor: colors.actionDangerText,
  },
  "colors.scrollbarThumb": {
    backgroundColor: colors.scrollbarThumb,
  },
  "colors.scrollbarThumbHover": {
    backgroundColor: colors.scrollbarThumbHover,
  },
  "colors.transparent": {
    backgroundColor: colors.transparent,
  },
  "colors.black": {
    backgroundColor: colors.black,
  },
  "colors.white": {
    backgroundColor: colors.white,
  },
  "colors.overlay": {
    backgroundColor: colors.overlay,
  },
  "colors.backgroundAlpha60": {
    backgroundColor: colors.backgroundAlpha60,
  },
  "colors.backgroundAlpha70": {
    backgroundColor: colors.backgroundAlpha70,
  },
  "colors.backgroundAlpha80": {
    backgroundColor: colors.backgroundAlpha80,
  },
  "colors.backgroundOpaque95": {
    backgroundColor: colors.backgroundOpaque95,
  },
  "colors.surfaceSubtleAlpha20": {
    backgroundColor: colors.surfaceSubtleAlpha20,
  },
  "colors.surfaceSubtleAlpha35": {
    backgroundColor: colors.surfaceSubtleAlpha35,
  },
  "colors.surfaceSubtleAlpha50": {
    backgroundColor: colors.surfaceSubtleAlpha50,
  },
  "colors.surfaceSubtleAlpha60": {
    backgroundColor: colors.surfaceSubtleAlpha60,
  },
  "colors.surfaceSubtleAlpha70": {
    backgroundColor: colors.surfaceSubtleAlpha70,
  },
  "colors.surfaceAlpha50": {
    backgroundColor: colors.surfaceAlpha50,
  },
  "colors.surfaceAlpha70": {
    backgroundColor: colors.surfaceAlpha70,
  },
  "colors.surfaceHoverAlpha60": {
    backgroundColor: colors.surfaceHoverAlpha60,
  },
  "colors.borderAlpha30": {
    backgroundColor: colors.borderAlpha30,
  },
  "colors.borderAlpha35": {
    backgroundColor: colors.borderAlpha35,
  },
  "colors.borderAlpha40": {
    backgroundColor: colors.borderAlpha40,
  },
  "colors.borderAlpha50": {
    backgroundColor: colors.borderAlpha50,
  },
  "colors.borderAlpha55": {
    backgroundColor: colors.borderAlpha55,
  },
  "colors.borderAlpha60": {
    backgroundColor: colors.borderAlpha60,
  },
  "colors.borderAlpha70": {
    backgroundColor: colors.borderAlpha70,
  },
  "colors.borderAlpha75": {
    backgroundColor: colors.borderAlpha75,
  },
  "colors.accentSurfaceAlpha10": {
    backgroundColor: colors.accentSurfaceAlpha10,
  },
  "colors.accentSurfaceAlpha15": {
    backgroundColor: colors.accentSurfaceAlpha15,
  },
  "colors.accentSurfaceAlpha20": {
    backgroundColor: colors.accentSurfaceAlpha20,
  },
  "colors.accentSurfaceAlpha30": {
    backgroundColor: colors.accentSurfaceAlpha30,
  },
  "colors.accentSurfaceAlpha40": {
    backgroundColor: colors.accentSurfaceAlpha40,
  },
  "colors.accentSurfaceAlpha60": {
    backgroundColor: colors.accentSurfaceAlpha60,
  },
  "colors.accentAlpha15": {
    backgroundColor: colors.accentAlpha15,
  },
  "colors.accentAlpha30": {
    backgroundColor: colors.accentAlpha30,
  },
  "colors.accentAlpha40": {
    backgroundColor: colors.accentAlpha40,
  },
  "colors.accentAlpha70": {
    backgroundColor: colors.accentAlpha70,
  },
  "colors.accentAlpha80": {
    backgroundColor: colors.accentAlpha80,
  },
  "colors.accentAlpha90": {
    backgroundColor: colors.accentAlpha90,
  },
  "colors.accentSoftAlpha15": {
    backgroundColor: colors.accentSoftAlpha15,
  },
  "colors.accentSoftAlpha40": {
    backgroundColor: colors.accentSoftAlpha40,
  },
  "colors.mediaOverlay20": {
    backgroundColor: colors.mediaOverlay20,
  },
  "colors.mediaOverlay30": {
    backgroundColor: colors.mediaOverlay30,
  },
  "colors.mediaControl": {
    backgroundColor: colors.mediaControl,
  },
  "colors.videoBadgeSurface": {
    backgroundColor: colors.videoBadgeSurface,
  },
  "colors.videoBadgeText": {
    backgroundColor: colors.videoBadgeText,
  },
  "colors.articleBadgeSurface": {
    backgroundColor: colors.articleBadgeSurface,
  },
  "colors.articleBadgeText": {
    backgroundColor: colors.articleBadgeText,
  },
  "colors.imageBadgeSurface": {
    backgroundColor: colors.imageBadgeSurface,
  },
  "colors.imageBadgeText": {
    backgroundColor: colors.imageBadgeText,
  },
  "colors.gifBadgeSurface": {
    backgroundColor: colors.gifBadgeSurface,
  },
  "colors.gifBadgeText": {
    backgroundColor: colors.gifBadgeText,
  },
  "spacing.none": {
    width: spacing.none,
  },
  "spacing.xxs": {
    width: spacing.xxs,
  },
  "spacing.xs": {
    width: spacing.xs,
  },
  "spacing.sm": {
    width: spacing.sm,
  },
  "spacing.md": {
    width: spacing.md,
  },
  "spacing.lg": {
    width: spacing.lg,
  },
  "spacing.xl": {
    width: spacing.xl,
  },
  "spacing.xxl": {
    width: spacing.xxl,
  },
  "spacing.xxxl": {
    width: spacing.xxxl,
  },
  "fontFamilies.sans": {
    fontFamily: fontFamilies.sans,
  },
  "fontFamilies.mono": {
    fontFamily: fontFamilies.mono,
  },
  "fontSizes.caption": {
    fontSize: fontSizes.caption,
  },
  "fontSizes.label": {
    fontSize: fontSizes.label,
  },
  "fontSizes.bodySmall": {
    fontSize: fontSizes.bodySmall,
  },
  "fontSizes.body": {
    fontSize: fontSizes.body,
  },
  "fontSizes.bodyLarge": {
    fontSize: fontSizes.bodyLarge,
  },
  "fontSizes.titleSmall": {
    fontSize: fontSizes.titleSmall,
  },
  "fontSizes.title": {
    fontSize: fontSizes.title,
  },
  "fontSizes.heading": {
    fontSize: fontSizes.heading,
  },
  "fontSizes.displaySmall": {
    fontSize: fontSizes.displaySmall,
  },
  "fontSizes.display": {
    fontSize: fontSizes.display,
  },
  "fontSizes.displayLarge": {
    fontSize: fontSizes.displayLarge,
  },
  "fontWeights.regular": {
    fontWeight: fontWeights.regular,
  },
  "fontWeights.medium": {
    fontWeight: fontWeights.medium,
  },
  "fontWeights.semibold": {
    fontWeight: fontWeights.semibold,
  },
  "fontWeights.bold": {
    fontWeight: fontWeights.bold,
  },
  "fontWeights.extraBold": {
    fontWeight: fontWeights.extraBold,
  },
  "lineHeights.none": {
    lineHeight: lineHeights.none,
  },
  "lineHeights.normal": {
    lineHeight: lineHeights.normal,
  },
  "lineHeights.tight": {
    lineHeight: lineHeights.tight,
  },
  "lineHeights.snug": {
    lineHeight: lineHeights.snug,
  },
  "lineHeights.relaxed": {
    lineHeight: lineHeights.relaxed,
  },
  "lineHeights.line16": {
    lineHeight: lineHeights.line16,
  },
  "lineHeights.line20": {
    lineHeight: lineHeights.line20,
  },
  "lineHeights.line24": {
    lineHeight: lineHeights.line24,
  },
  "lineHeights.line28": {
    lineHeight: lineHeights.line28,
  },
  "lineHeights.line32": {
    lineHeight: lineHeights.line32,
  },
  "lineHeights.line36": {
    lineHeight: lineHeights.line36,
  },
  "letterSpacing.display": {
    letterSpacing: letterSpacing.display,
  },
  "letterSpacing.wide": {
    letterSpacing: letterSpacing.wide,
  },
  "letterSpacing.wider": {
    letterSpacing: letterSpacing.wider,
  },
  "letterSpacing.label": {
    letterSpacing: letterSpacing.label,
  },
  "letterSpacing.labelWide": {
    letterSpacing: letterSpacing.labelWide,
  },
  "letterSpacing.eyebrow": {
    letterSpacing: letterSpacing.eyebrow,
  },
  "radii.none": {
    borderRadius: radii.none,
  },
  "radii.xxs": {
    borderRadius: radii.xxs,
  },
  "radii.xs": {
    borderRadius: radii.xs,
  },
  "radii.sm": {
    borderRadius: radii.sm,
  },
  "radii.md": {
    borderRadius: radii.md,
  },
  "radii.lg": {
    borderRadius: radii.lg,
  },
  "radii.xl": {
    borderRadius: radii.xl,
  },
  "radii.circle": {
    borderRadius: radii.circle,
  },
  "radii.pill": {
    borderRadius: radii.pill,
  },
  "shadows.none": {
    boxShadow: shadows.none,
  },
  "shadows.elevationXs": {
    boxShadow: shadows.elevationXs,
  },
  "shadows.elevationSm": {
    boxShadow: shadows.elevationSm,
  },
  "shadows.elevationMd": {
    boxShadow: shadows.elevationMd,
  },
  "shadows.elevationLg": {
    boxShadow: shadows.elevationLg,
  },
  "shadows.media": {
    boxShadow: shadows.media,
  },
  "shadows.mediaHover": {
    boxShadow: shadows.mediaHover,
  },
  "shadows.mediaStrong": {
    boxShadow: shadows.mediaStrong,
  },
  "shadows.tooltip": {
    boxShadow: shadows.tooltip,
  },
  "shadows.focus": {
    boxShadow: shadows.focus,
  },
  "shadows.focusOffsetBackground": {
    boxShadow: shadows.focusOffsetBackground,
  },
  "shadows.focusOffsetSurface": {
    boxShadow: shadows.focusOffsetSurface,
  },
  "shadows.accentOutline": {
    boxShadow: shadows.accentOutline,
  },
  "shadows.accentSubtleOutline": {
    boxShadow: shadows.accentSubtleOutline,
  },
  "shadows.raisedAccent": {
    boxShadow: shadows.raisedAccent,
  },
  "shadows.accentInset": {
    boxShadow: shadows.accentInset,
  },
  "shadows.currentColorFocus": {
    boxShadow: shadows.currentColorFocus,
  },
  "shadows.avatarRing": {
    boxShadow: shadows.avatarRing,
  },
  "shadows.avatarRingSmall": {
    boxShadow: shadows.avatarRingSmall,
  },
});
