import ts from "typescript";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const modules = [
  "Colors",
  "Spacing",
  "Typography",
  "BorderRadius",
  "Shadows",
  "Motion",
  "Layout",
  "Breakpoints",
];
export function generateDesignSystem() {
  const manifest = {};
  const imports = [];
  const styles = [];
  const properties = {
    colors: "backgroundColor",
    spacing: "width",
    radii: "borderRadius",
    shadows: "boxShadow",
    fontSizes: "fontSize",
    fontWeights: "fontWeight",
    lineHeights: "lineHeight",
    letterSpacing: "letterSpacing",
    fontFamilies: "fontFamily",
  };
  for (const module of modules) {
    const filename = new URL(`src/styles/${module}.stylex.ts`, root);
    const source = ts.createSourceFile(
      filename.pathname,
      readFileSync(filename, "utf8"),
      ts.ScriptTarget.Latest,
      true,
    );
    for (const statement of source.statements) {
      if (!ts.isVariableStatement(statement)) continue;
      for (const declaration of statement.declarationList.declarations) {
        const call = declaration.initializer;
        if (
          !call ||
          !ts.isCallExpression(call) ||
          !ts.isPropertyAccessExpression(call.expression) ||
          !["defineVars", "defineConsts"].includes(call.expression.name.text)
        )
          continue;
        const name = declaration.name.getText(source);
        const object = call.arguments[0];
        if (!object || !ts.isObjectLiteralExpression(object))
          throw new Error(`Unsupported token declaration: ${name}`);
        manifest[name] = {};
        for (const property of object.properties) {
          if (
            !ts.isPropertyAssignment(property) ||
            !property.name ||
            property.name.kind === ts.SyntaxKind.ComputedPropertyName
          )
            throw new Error(`Unsupported token in ${name}`);
          const key = property.name.text;
          const value = property.initializer;
          if (!ts.isStringLiteral(value) && !ts.isNumericLiteral(value))
            throw new Error(`Expected literal: ${name}.${key}`);
          manifest[name][key] = ts.isNumericLiteral(value)
            ? Number(value.text)
            : value.text;
          if (properties[name])
            styles.push(
              `  "${name}.${key}": {\n    ${properties[name]}: ${name}.${key},\n  },`,
            );
        }
        if (properties[name])
          imports.push(
            `import { ${name} } from "../../styles/${module}.stylex";`,
          );
      }
    }
  }
  // Resolve recipe references as documentation, without evaluating source code.
  const recipeSource = ts.createSourceFile(
    "Fonts.stylex.ts",
    readFileSync(new URL("src/styles/Fonts.stylex.ts", root), "utf8"),
    ts.ScriptTarget.Latest,
    true,
  );
  function resolve(node) {
    if (ts.isStringLiteral(node)) return node.text;
    if (ts.isNumericLiteral(node)) return Number(node.text);
    if (
      ts.isPropertyAccessExpression(node) &&
      ts.isIdentifier(node.expression)
    ) {
      const value = manifest[node.expression.text]?.[node.name.text];
      if (value === undefined)
        throw new Error(
          `Unknown recipe reference: ${node.getText(recipeSource)}`,
        );
      return value;
    }
    if (ts.isObjectLiteralExpression(node)) {
      return Object.fromEntries(
        node.properties.map((property) => {
          if (!ts.isPropertyAssignment(property))
            throw new Error("Unsupported font recipe");
          const key = ts.isComputedPropertyName(property.name)
            ? resolve(property.name.expression)
            : property.name.text;
          return [key, resolve(property.initializer)];
        }),
      );
    }
    throw new Error(
      `Unsupported recipe expression: ${node.getText(recipeSource)}`,
    );
  }
  for (const statement of recipeSource.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    for (const declaration of statement.declarationList.declarations) {
      if (
        declaration.name.getText(recipeSource) === "fonts" &&
        ts.isCallExpression(declaration.initializer)
      ) {
        manifest.fonts = resolve(declaration.initializer.arguments[0]);
      }
    }
  }
  const files = {
    "src/tools/design-system/data/tokens.generated.json":
      JSON.stringify(manifest, null, 2) + "\n",
    "src/tools/design-system/specimens.generated.ts":
      '// Generated by scripts/design-system.mjs. Do not edit.\nimport * as stylex from "@stylexjs/stylex";\n' +
      imports.join("\n") +
      "\n\nexport const specimens = stylex.create({\n" +
      styles.join("\n") +
      "\n});\n",
  };
  for (const [path, content] of Object.entries(files)) {
    const url = new URL(path, root);
    let previous;
    try {
      previous = readFileSync(url, "utf8");
    } catch {
      /* First generation. */
    }
    if (previous !== content) writeFileSync(url, content);
  }
}
export function designSystemPlugin() {
  return {
    name: "design-system-tokens",
    buildStart() {
      generateDesignSystem();
    },
    configureServer(server) {
      const directory = fileURLToPath(new URL("src/styles/", root));
      server.watcher.on("change", (file) => {
        if (!file.startsWith(directory) || !file.endsWith(".stylex.ts")) return;
        try {
          generateDesignSystem();
        } catch (error) {
          // Invalid edits should show Vite's overlay, not terminate the server.
          server.config.logger.error(error.message);
          server.ws.send({
            type: "error",
            err: { message: error.message, stack: error.stack },
          });
        }
      });
    },
  };
}
if (process.argv[1] === fileURLToPath(import.meta.url)) generateDesignSystem();
